### ISSUE TITLE
Feature #1: User can view a list of Harry Potter character cards

### ISSUE THREAD

**Issue by hannahhoanggg** [hannahhoanggg/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a list of Harry Potter character cards. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user opens up the web browser, the website will display all of the Harry Potter character cards. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2023-08-15 143345](https://github.com/hannahhoanggg/ajax-project/assets/136301731/0cdbfe4a-f0d3-4099-90aa-a6801740447d)
![Screenshot 2023-08-15 143401](https://github.com/hannahhoanggg/ajax-project/assets/136301731/ba9861d0-4714-4d05-8574-4e1b314b63f2)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create the HTML for the navigation bar so it matches the wireframe.
- [x] Make sure to create one card for each character.
- [x] Assign a `div[class = character-container]` to hold the characters. 
- [x] Add a `div[data-view="character-view"]` to the HTML.
- [x] Ensure that the character list looks good on both mobile-sized and desktop-sized screens. 
- [x] Create a new XMLHttpRequest() to request for characters data on specific characters from the potterdb API website: https://api.potterdb.com/v1/characters or https://api.potterdb.com/v1/characters/harry-potter.
- [x]  Define a function `renderHPCharacters` that takes a `character` object and returns a DOM tree in the HTML.
- [x] Use a loop to create a DOM tree to display all of the Harry Potter character images.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
